name: ServerConnectorCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [ 20 ]

    steps:
    # Checkout
    - uses: actions/checkout@v4

    # Setup node
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    # Install from npm
    - run: npm install

    # Build the component
    - run: npm run build
    # Run Unit tests
    - name: Run Unit tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test

    # Run UI tests
    - name: Run UI tests
      if: runner.os == 'Linux'
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run public-ui-test

    # Archive test artifacts
    - name: Archiving test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with: 
        name: artifacts-${{ matrix.os }}
        path: |
          test-resources/screenshots/*.png
        retention-days: 2

    # Upload code coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/coverage-final.json
            
